# Module with strings in multiple languages

class czech:
    loading = "Načítání..."
    settings = "Nastavení"
    nextDay = "Další den"
    prevDay = "Předchozí den"
    allCals = "Všechny kalendáře:"
    calsToSee = "Kalendáře k zobrazení:"
    back = "Zpět"
    language = "Jazyk rozhraní:"
    configError = "Nepodařilo se načíst konfigurační soubor"
    daysOfWeek = ["Pondělí", "Úterý", "Středa", "Čtvrtek", "Pátek", "Sobota", "Neděle"]
    noEvents = "Tento den nemáš žádné události."
    today = "Dnes"
    allday = "Celodenní"
    months = ["Leden", "Únor", "Březen", "Duben", "Květen", "Červen", "Červenec", "Srpen", "Září", "Říjen", "Listopad", "Prosinec"]
    exit = "Konec"
    jump = "Přejít na..."
    start = "Začátek: "
    end = "Konec: "
    location = "Umístění: "
    description = "Popis: "
    calendar = "Kalendář: "
    loginFailed = "Přihlášení se nepovedlo."
    somethingError = "Něco se nepovedlo, je reMarkable připojený k internetu? "
    retry = "Zkusit znovu"

class english:
    loading = "Loading..."
    settings = "Settings"
    nextDay = "Next day"
    prevDay = "Previous day"
    allCals = "All calendars:"
    calsToSee = "Calendars to display:"
    back = "Back"
    language = "Language:"
    configError = "Error loading config file"
    daysOfWeek = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    noEvents = "No events."
    today = "Today"
    allday = "All-day"
    months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    exit = "Exit"
    jump = "Go to..."
    start = "Starts: "
    end = "Ends: "
    location = "Location: "
    description = "Description: "
    calendar = "Calendar: "
    loginFailed = "Login failed."
    somethingError = "Something went wrong, is reMarkable connected to the internet?"
    retry = "Retry"
